services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sim_db'
      - 'MYSQL_PASSWORD=simUser'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=simUser'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: openjdk:17-jdk-slim
    container_name: spring-boot-sim
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sim_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    working_dir: /app
#  command: ./mvn spring-boot:run

volumes:
  db_data: