name: Deploy SIM Application

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Adjust links in index.html
        run: |
          sed -i 's|<base href=".*">|<base href="/sim/">|g' ./target/classes/static/index.html

      #      - name: Deploy to GitHub Pages
      #        uses: peaceiris/actions-gh-pages@v3
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          publish_dir: ./target/classes/static
      #          publish_branch: gh-pages

      - name: Create and update frontend branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin
          git checkout -B frontend
          if [ -d "./target/classes/static" ]; then
            rm -rf *
            cp -r ./target/classes/static/* .
            git add .
            git commit -m "Update frontend from master"
            git push origin frontend --force
          else
            echo "Static directory not found. Skipping frontend branch update."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/thommadurasahan/school-inventory-management:latest